kind: token
version: v2
metadata:
  # name will be specified in the `tbot` to use this token
  name: tbot
spec:
  roles: [Bot]
  # bot_name should match the name of the bot created earlier in this guide.
  bot_name: tbot
  join_method: kubernetes
  kubernetes:
    # static_jwks configures the Auth Service to validate the JWT presented by
    # `tbot` using the public key from a statically configured JWKS.
    type: static_jwks
    static_jwks:
      jwks: |
        {"keys":[{"use":"sig","kty":"RSA","kid":"GxiyNcLidnewxesvOcwIApstRO-qzlEU7tm8_QhTlHU","alg":"RS256","n":"oGG9FdgkHOBTXB1tZNUyxj191OaRzMI6tLlN5knZ-rS6kFRTqq539gPyLLN3g7V5gkHK6Azj5o_8BNS0Uc2GPeSH2P0xXJvQ4GMi0tKOEVyIbPa6Svtbmj2mcIHqruRxJ5bd5u1ygFg7tAFPnGa_V7e-EJJlTVAYeu-1mBq5qJEX6FwHWaPYjEHNzALRX5nHWI8mUb67c2BRRjvfNpb65LUQUwVQZ8YLA4KLDu6AjNyTPtN2QW_aDRhHkbhIZ95bzh4OTFNyCqlIwM23EvgAuGzEMd00s-zJll5y2hdaQ03-B8lLuKDYbT8GJ2SBMEADOTw2tfaROAPyD3aArfJQBw","e":"AQAB"}]}
    # allow specifies the rules by which the Auth Service determines if `tbot`
    # should be allowed to join.
    allow:
    - service_account: "tbot:tbot" # service_account

